FROM node:22-alpine
RUN corepack enable
WORKDIR /app

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json tsconfig.base.json turbo.json ./
COPY packages/core/package.json ./packages/core/
COPY packages/woo/package.json ./packages/woo/
COPY apps/web/package.json ./apps/web/

RUN pnpm install
COPY . .
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
CMD ["pnpm", "dev"]
